// Registers all Phosphor icons used across snippet demo pages.
// Uses ?raw imports so Vite inlines the SVG strings at build time.
import { registerIcon } from '@nonoun/native-ui';

// Regular weight
import arrowClockwise from '@phosphor-icons/core/assets/regular/arrow-clockwise.svg?raw';
import arrowCounterClockwise from '@phosphor-icons/core/assets/regular/arrow-counter-clockwise.svg?raw';
import arrowDown from '@phosphor-icons/core/assets/regular/arrow-down.svg?raw';
import arrowLeft from '@phosphor-icons/core/assets/regular/arrow-left.svg?raw';
import arrowRight from '@phosphor-icons/core/assets/regular/arrow-right.svg?raw';
import arrowUp from '@phosphor-icons/core/assets/regular/arrow-up.svg?raw';
import arrowsOut from '@phosphor-icons/core/assets/regular/arrows-out.svg?raw';
import bell from '@phosphor-icons/core/assets/regular/bell.svg?raw';
import bookOpen from '@phosphor-icons/core/assets/regular/book-open.svg?raw';
import calendar from '@phosphor-icons/core/assets/regular/calendar.svg?raw';
import caretDown from '@phosphor-icons/core/assets/regular/caret-down.svg?raw';
import caretLeft from '@phosphor-icons/core/assets/regular/caret-left.svg?raw';
import caretRight from '@phosphor-icons/core/assets/regular/caret-right.svg?raw';
import caretUp from '@phosphor-icons/core/assets/regular/caret-up.svg?raw';
import caretUpDown from '@phosphor-icons/core/assets/regular/caret-up-down.svg?raw';
import chartBar from '@phosphor-icons/core/assets/regular/chart-bar.svg?raw';
import chatCircle from '@phosphor-icons/core/assets/regular/chat-circle.svg?raw';
import chatDots from '@phosphor-icons/core/assets/regular/chat-dots.svg?raw';
import check from '@phosphor-icons/core/assets/regular/check.svg?raw';
import checkCircle from '@phosphor-icons/core/assets/regular/check-circle.svg?raw';
import clipboard from '@phosphor-icons/core/assets/regular/clipboard.svg?raw';
import clipboardText from '@phosphor-icons/core/assets/regular/clipboard-text.svg?raw';
import code from '@phosphor-icons/core/assets/regular/code.svg?raw';
import copy from '@phosphor-icons/core/assets/regular/copy.svg?raw';
import creditCard from '@phosphor-icons/core/assets/regular/credit-card.svg?raw';
import currencyDollar from '@phosphor-icons/core/assets/regular/currency-dollar.svg?raw';
import dotsThree from '@phosphor-icons/core/assets/regular/dots-three.svg?raw';
import download from '@phosphor-icons/core/assets/regular/download.svg?raw';
import envelope from '@phosphor-icons/core/assets/regular/envelope.svg?raw';
import envelopeSimple from '@phosphor-icons/core/assets/regular/envelope-simple.svg?raw';
import eye from '@phosphor-icons/core/assets/regular/eye.svg?raw';
import fileText from '@phosphor-icons/core/assets/regular/file-text.svg?raw';
import floppyDisk from '@phosphor-icons/core/assets/regular/floppy-disk.svg?raw';
import folder from '@phosphor-icons/core/assets/regular/folder.svg?raw';
import folderOpen from '@phosphor-icons/core/assets/regular/folder-open.svg?raw';
import funnel from '@phosphor-icons/core/assets/regular/funnel.svg?raw';
import gear from '@phosphor-icons/core/assets/regular/gear.svg?raw';
import githubLogo from '@phosphor-icons/core/assets/regular/github-logo.svg?raw';
import googleLogo from '@phosphor-icons/core/assets/regular/google-logo.svg?raw';
import gridFour from '@phosphor-icons/core/assets/regular/grid-four.svg?raw';
import heart from '@phosphor-icons/core/assets/regular/heart.svg?raw';
import house from '@phosphor-icons/core/assets/regular/house.svg?raw';
import info from '@phosphor-icons/core/assets/regular/info.svg?raw';
import lightning from '@phosphor-icons/core/assets/regular/lightning.svg?raw';
import list from '@phosphor-icons/core/assets/regular/list.svg?raw';
import listBullets from '@phosphor-icons/core/assets/regular/list-bullets.svg?raw';
import listNumbers from '@phosphor-icons/core/assets/regular/list-numbers.svg?raw';
import lock from '@phosphor-icons/core/assets/regular/lock.svg?raw';
import magnifyingGlass from '@phosphor-icons/core/assets/regular/magnifying-glass.svg?raw';
import magnifyingGlassMinus from '@phosphor-icons/core/assets/regular/magnifying-glass-minus.svg?raw';
import magnifyingGlassPlus from '@phosphor-icons/core/assets/regular/magnifying-glass-plus.svg?raw';
import mapPin from '@phosphor-icons/core/assets/regular/map-pin.svg?raw';
import microphone from '@phosphor-icons/core/assets/regular/microphone.svg?raw';
import pkg from '@phosphor-icons/core/assets/regular/package.svg?raw';
import pencilSimple from '@phosphor-icons/core/assets/regular/pencil-simple.svg?raw';
import percent from '@phosphor-icons/core/assets/regular/percent.svg?raw';
import phone from '@phosphor-icons/core/assets/regular/phone.svg?raw';
import play from '@phosphor-icons/core/assets/regular/play.svg?raw';
import plus from '@phosphor-icons/core/assets/regular/plus.svg?raw';
import printer from '@phosphor-icons/core/assets/regular/printer.svg?raw';
import pulse from '@phosphor-icons/core/assets/regular/pulse.svg?raw';
import receipt from '@phosphor-icons/core/assets/regular/receipt.svg?raw';
import repeat from '@phosphor-icons/core/assets/regular/repeat.svg?raw';
import rocketLaunch from '@phosphor-icons/core/assets/regular/rocket-launch.svg?raw';
import scissors from '@phosphor-icons/core/assets/regular/scissors.svg?raw';
import selectionAll from '@phosphor-icons/core/assets/regular/selection-all.svg?raw';
import shieldCheck from '@phosphor-icons/core/assets/regular/shield-check.svg?raw';
import shoppingBag from '@phosphor-icons/core/assets/regular/shopping-bag.svg?raw';
import shoppingCart from '@phosphor-icons/core/assets/regular/shopping-cart.svg?raw';
import shuffle from '@phosphor-icons/core/assets/regular/shuffle.svg?raw';
import signOut from '@phosphor-icons/core/assets/regular/sign-out.svg?raw';
import skipBack from '@phosphor-icons/core/assets/regular/skip-back.svg?raw';
import skipForward from '@phosphor-icons/core/assets/regular/skip-forward.svg?raw';
import sortAscending from '@phosphor-icons/core/assets/regular/sort-ascending.svg?raw';
import speakerHigh from '@phosphor-icons/core/assets/regular/speaker-high.svg?raw';
import star from '@phosphor-icons/core/assets/regular/star.svg?raw';
import terminal from '@phosphor-icons/core/assets/regular/terminal.svg?raw';
import textAlignCenter from '@phosphor-icons/core/assets/regular/text-align-center.svg?raw';
import textAlignLeft from '@phosphor-icons/core/assets/regular/text-align-left.svg?raw';
import textAlignRight from '@phosphor-icons/core/assets/regular/text-align-right.svg?raw';
import textB from '@phosphor-icons/core/assets/regular/text-b.svg?raw';
import textItalic from '@phosphor-icons/core/assets/regular/text-italic.svg?raw';
import textStrikethrough from '@phosphor-icons/core/assets/regular/text-strikethrough.svg?raw';
import textUnderline from '@phosphor-icons/core/assets/regular/text-underline.svg?raw';
import trash from '@phosphor-icons/core/assets/regular/trash.svg?raw';
import trendDown from '@phosphor-icons/core/assets/regular/trend-down.svg?raw';
import trendUp from '@phosphor-icons/core/assets/regular/trend-up.svg?raw';
import user from '@phosphor-icons/core/assets/regular/user.svg?raw';
import userPlus from '@phosphor-icons/core/assets/regular/user-plus.svg?raw';
import users from '@phosphor-icons/core/assets/regular/users.svg?raw';
import warning from '@phosphor-icons/core/assets/regular/warning.svg?raw';
import warningCircle from '@phosphor-icons/core/assets/regular/warning-circle.svg?raw';
import x from '@phosphor-icons/core/assets/regular/x.svg?raw';
import xCircle from '@phosphor-icons/core/assets/regular/x-circle.svg?raw';

// Layout shell icons (used in SidebarLayout.astro and layout.ts, not in snippets)
import compass from '@phosphor-icons/core/assets/regular/compass.svg?raw';
import cpu from '@phosphor-icons/core/assets/regular/cpu.svg?raw';
import cube from '@phosphor-icons/core/assets/regular/cube.svg?raw';
import moon from '@phosphor-icons/core/assets/regular/moon.svg?raw';
import sidebarSimple from '@phosphor-icons/core/assets/regular/sidebar-simple.svg?raw';
import sparkle from '@phosphor-icons/core/assets/regular/sparkle.svg?raw';
import squaresFour from '@phosphor-icons/core/assets/regular/squares-four.svg?raw';
import slidersHorizontal from '@phosphor-icons/core/assets/regular/sliders-horizontal.svg?raw';
import sun from '@phosphor-icons/core/assets/regular/sun.svg?raw';

// Fill weight
import chatDotsFill from '@phosphor-icons/core/assets/fill/chat-dots-fill.svg?raw';
import codeFill from '@phosphor-icons/core/assets/fill/code-fill.svg?raw';
import dotsThreeOutlineFill from '@phosphor-icons/core/assets/fill/dots-three-outline-fill.svg?raw';
import sidebarSimpleFill from '@phosphor-icons/core/assets/fill/sidebar-simple-fill.svg?raw';
import slidersHorizontalFill from '@phosphor-icons/core/assets/fill/sliders-horizontal-fill.svg?raw';

registerIcon('arrow-clockwise', arrowClockwise);
registerIcon('arrow-counter-clockwise', arrowCounterClockwise);
registerIcon('arrow-down', arrowDown);
registerIcon('arrow-left', arrowLeft);
registerIcon('arrow-right', arrowRight);
registerIcon('arrow-up', arrowUp);
registerIcon('arrows-out', arrowsOut);
registerIcon('bell', bell);
registerIcon('book-open', bookOpen);
registerIcon('calendar', calendar);
registerIcon('caret-down', caretDown);
registerIcon('caret-left', caretLeft);
registerIcon('caret-right', caretRight);
registerIcon('caret-up', caretUp);
registerIcon('caret-up-down', caretUpDown);
registerIcon('chart-bar', chartBar);
registerIcon('chat-circle', chatCircle);
registerIcon('chat-dots', chatDots);
registerIcon('check', check);
registerIcon('check-circle', checkCircle);
registerIcon('clipboard', clipboard);
registerIcon('clipboard-text', clipboardText);
registerIcon('code', code);
registerIcon('copy', copy);
registerIcon('credit-card', creditCard);
registerIcon('currency-dollar', currencyDollar);
registerIcon('dots-three', dotsThree);
registerIcon('download', download);
registerIcon('envelope', envelope);
registerIcon('envelope-simple', envelopeSimple);
registerIcon('eye', eye);
registerIcon('file-text', fileText);
registerIcon('floppy-disk', floppyDisk);
registerIcon('folder', folder);
registerIcon('folder-open', folderOpen);
registerIcon('funnel', funnel);
registerIcon('gear', gear);
registerIcon('github-logo', githubLogo);
registerIcon('google-logo', googleLogo);
registerIcon('grid-four', gridFour);
registerIcon('heart', heart);
registerIcon('house', house);
registerIcon('info', info);
registerIcon('lightning', lightning);
registerIcon('list', list);
registerIcon('list-bullets', listBullets);
registerIcon('list-numbers', listNumbers);
registerIcon('lock', lock);
registerIcon('magnifying-glass', magnifyingGlass);
registerIcon('magnifying-glass-minus', magnifyingGlassMinus);
registerIcon('magnifying-glass-plus', magnifyingGlassPlus);
registerIcon('map-pin', mapPin);
registerIcon('microphone', microphone);
registerIcon('package', pkg);
registerIcon('pencil-simple', pencilSimple);
registerIcon('percent', percent);
registerIcon('phone', phone);
registerIcon('play', play);
registerIcon('plus', plus);
registerIcon('printer', printer);
registerIcon('pulse', pulse);
registerIcon('receipt', receipt);
registerIcon('repeat', repeat);
registerIcon('rocket-launch', rocketLaunch);
registerIcon('scissors', scissors);
registerIcon('selection-all', selectionAll);
registerIcon('shield-check', shieldCheck);
registerIcon('shopping-bag', shoppingBag);
registerIcon('shopping-cart', shoppingCart);
registerIcon('shuffle', shuffle);
registerIcon('sign-out', signOut);
registerIcon('skip-back', skipBack);
registerIcon('skip-forward', skipForward);
registerIcon('sort-ascending', sortAscending);
registerIcon('speaker-high', speakerHigh);
registerIcon('star', star);
registerIcon('terminal', terminal);
registerIcon('text-align-center', textAlignCenter);
registerIcon('text-align-left', textAlignLeft);
registerIcon('text-align-right', textAlignRight);
registerIcon('text-b', textB);
registerIcon('text-italic', textItalic);
registerIcon('text-strikethrough', textStrikethrough);
registerIcon('text-underline', textUnderline);
registerIcon('trash', trash);
registerIcon('trend-down', trendDown);
registerIcon('trend-up', trendUp);
registerIcon('user', user);
registerIcon('user-plus', userPlus);
registerIcon('users', users);
registerIcon('warning', warning);
registerIcon('warning-circle', warningCircle);
registerIcon('x', x);
registerIcon('x-circle', xCircle);
registerIcon('compass', compass);
registerIcon('cpu', cpu);
registerIcon('cube', cube);
registerIcon('moon', moon);
registerIcon('sidebar-simple', sidebarSimple);
registerIcon('sparkle', sparkle);
registerIcon('squares-four', squaresFour);
registerIcon('sun', sun);
registerIcon('chat-dots-fill', chatDotsFill);
registerIcon('code-fill', codeFill);
registerIcon('dots-three-outline-fill', dotsThreeOutlineFill);
registerIcon('sidebar-simple-fill', sidebarSimpleFill);
registerIcon('sliders-horizontal', slidersHorizontal);
registerIcon('sliders-horizontal-fill', slidersHorizontalFill);
